FROM python:3.9

WORKDIR /app

# Install backend dependencies
COPY requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libssl-dev libffi-dev python3-dev cargo
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend code
COPY . .

# Expose the backend port
EXPOSE 5000

# Start the backend
CMD ["python", "app.py"]